version: '1.0.0'

services:
  app:
    container_name: backend
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./:/home/app
    links:
      - mongodb
  
  mongodb:
    container_name: mongodb
    image: mongo:4
    attach: false
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    environment:
        - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
        - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  mongo: